### ISSUE TITLE
Identify existing tutorials for Casper Course

### ISSUE THREAD

**Issue by ShalmaliCL** [casper-network/docs#1014]
- Identify existing tutorials [per module ](https://casperlabs.atlassian.net/l/cp/HjBUBy0r)
- Create new cards if required to create new tutorials

**Comment by ShalmaliCL** [comment]
As per the team's feedback, changing the module 1 "Hello World" assignment to a native transfer.

Following are the existing articles/tutorials, we may refer to for module 1:

- [Creating Account and Keys ](https://docs.casper.network/concepts/accounts-and-keys/#creating-accounts-and-keys)
- [Funding the Testnet Account](https://docs.casper.network/users/testnet-faucet/)
- [Native transfer](https://docs.casper.network/resources/tutorials/advanced/list-cspr/#native-transfer)
- [Direct Token Transfer ](https://docs.casper.network/developers/cli/transfers/direct-token-transfer/) 
- [Token Transfer using Block Explorer](https://docs.casper.network/users/token-transfer/)

@ramujin @ACStoneCL - Please share your thoughts and feel free to add your input.
CC: @ACStoneCL -  I suggest we create another card to consolidate the above and put everything into sync.

**Comment by ramujin** [comment]
Thanks for identifying these links @ShalmaliCL! I think we can close this card and focus on the next steps for the next sprint. Some of the content is irrelevant for Module 1 since Karan suggested focusing purely on the block explorer without doing anything directly, but later modules will definitely be referring to it.
