### ISSUE TITLE
Create Custom ERC20 Deployment Guide

### ISSUE THREAD

**Issue by dylanireland** [casper-network/docs#161]
Creating ERC20 deployment guide for Casper users to allow them to easily install their own ERC20 token on the Casper mainnet. Exists as a branch of casper-network/docs.

**Comment by dylanireland** [comment]
Changed this guide from using `casper-client` to using the `casper-erc20-js-client`.

**Comment by ipopescu** [comment]
@dylanireland, I removed the estimate so that it doesn't impact the team's velocity. We welcome your contributions anytime you have a gap to write guides/docs!

**Comment by davidatwhiletrue** [comment]
Nice and easy to follow tutorial! 

I went through it without `casper-client` or any `rust` dependency installed in my system. Looks like the actual prerequisites are only NodeJs and a funded account. I would review this section to make it simpler to beginners.

On the other hand, the JS SDK offers a method to load a key pair only from the private file. Since now Casper Signer only offers to download the private key, it may make sense to use this method instead of the one that requires public and private key files.

```
const KEYS = Keys.Ed25519.loadKeyPairFromPrivateFile(
  "./keys/secret_key.pem"
);
```

**Comment by dylanireland** [comment]
@davidatwhiletrue Made this change, updates merged 👍
