### ISSUE TITLE
Explain how to estimate gas price

### ISSUE THREAD

**Issue by deuszex** [casper-network/docs#179]
Show how to estimate gas price and relating data of the written contracts before deployment. Add a paragraph in the documentation here https://docs.casperlabs.io/en/latest/dapp-dev-guide/deploying-contracts.html.

**Comment by ipopescu** [comment]
Returning this to the backlog. Due to the much-needed planning, and additional course work, I will not be able to take care of it this sprint.

**Comment by ramujin** [comment]
I'm unclear on the request here. We don't have a definitive way of knowing gas price other than running the deploy on the testnet (or NCTL) and seeing what it ended up costing before executing it on the mainnet.

**Comment by ipopescu** [comment]
@ramujin I was envisioning a paragraph explaining how to estimate gas price: "running the deploy on the testnet (or NCTL) and seeing what it ended up costing before executing it on the mainnet". Show the commands to deploy and a screenshot or two of the cost.
I will update the request to find a "definitive" way. 
We can point people from Discord to this section because I saw that many were asking about this. I hope the request is clearer now :). Thank you!

**Comment by ramujin** [comment]
I submitted a PR with the updated docs. Please review!
