### ISSUE TITLE
Navigation issues with docs

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#268]
Sometimes, when I hit this page, it shows up blank, even though I know there's a whole table of stuff on that page, because other times, it shows up with the table on it https://casper.network/docs/sdk.

- ![image.png](https://images.zenhubusercontent.com/60785891648deb2076a7ddc1/328d18f4-1c91-4dc0-b243-97683941a487)

Looks like its pulling down the content for the sub pages but not displaying.

- ![image (1).png](https://images.zenhubusercontent.com/60785891648deb2076a7ddc1/ecf7f2e7-28d9-4552-8d40-0364337a6a9f)

- ![image (2).png](https://images.zenhubusercontent.com/60785891648deb2076a7ddc1/3ed44031-65c6-4792-ba1d-8c6058e5cd49)

If you start from a different URL, search SDK, and click the client library link, it navigates to the SDK without a problem. But if you hit the URL directly, it doesn't always work.
If you load https://casper.network/docs/sdk, then click One of the client libraries and click back to Introduction it renders properly.

There are similar issues with https://casper.network/docs/tutorials and https://casper.network/docs/writing-contracts.
It seems like the logic doesn't like nested items in the left nav where it's meant to default to the first nested child.
If i had to guess, a DOM traversal issue on load, or something along those lines. It seems to be specific if you nav in via direct URL.

Workaround: if you put the trailing slash it seems to work: https://casper.network/docs/writing-contracts vs https://casper.network/docs/writing-contracts/.

Slack conversation: https://casperlabs-team.slack.com/archives/C0135SDEGUC/p1646345316734409?thread_ts=1646334118.337539&cid=C0135SDEGUC

**Comment by ipopescu** [comment]
@sd-ditoy, is it possible to get your help with this item?

**Comment by sd-ditoy** [comment]
I'll have a look at it. 
For your info: i can't see the slack conversation since i'm not part of your Slack. 
I don't think it will be super important though, since based on your description the issue is very clear.

**Comment by sd-ditoy** [comment]
At first i thought it was an issue with the current version (2.0.0-beta.14) of docusaurus. 
So i've updated the branch for this issue to the latest release (docusaurus 2.0.0-beta.17).

I've then created builds for both versions and ran them on a local nginx server. 
Both versions **don't** exhibit this behaviour at all.

At this point i'm assuming this might be a configuration issue on the web server. Since even the regular site seems to have this issue/behaviour, just in reverse. 

For example: https://casper.network/en/network works fine. 
While https://casper.network/en/network/ does not load properly.

I'm guessing the url rewrites rules that are configured on the nginx server may cause this problem. 
If you could provide me with details/credentials for the server, i could have a looksy, to determine if my assumptions.

**Comment by ipopescu** [comment]
Thank you for the analysis, @sd-ditoy!

**Comment by sd-ditoy** [comment]
I've had a lovely chat with @bradjohnl about this issue. This should eventually be resolved when the docs are deployed on github pages.

In the meantime i dug a bit more in the configuration of docusaurus and found a way to enforce trailing slashes (which would solve this issue). I will write more details about this within the PR.
