### ISSUE TITLE
Getting started refresh – video

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#316]
The Getting started instructions in module 1 have changed recently. The guide has been updated, but the video and powerpoint need to be updated as well.
https://docs.casperlabs.io/en/latest/dapp-dev-guide/setup-of-rust-contract-sdk.html

**Comment by ramujin** [comment]
Updated recording is located here: https://drive.google.com/file/d/1hA_MjeZzVcWObdVdVdPOA_vyNuDze0sK/view?usp=sharing

Note: Instead of re-recording the entire video, I largely removed segments that pertained to the old process of using "cargo test" instead of "make test" when doing the demo portion because otherwise I would have to completely run through the entire sequence again in a new recording.

Please provide feedback on if this video is acceptable or if we should start from scratch and make a new recording using the latest release.

**Comment by ipopescu** [comment]
@ramujin thank you for updating the video! I think it flows really well and we should use it. The way you worked with the testing slide is a good option for future recordings.

**Comment by ipopescu** [comment]
@ramujin I've updated the documentation to reflect the new video link: https://github.com/casper-network/docs/pull/327.
Please review. Once that PR is merged, we can close this card. Thanks so much for your help!
