### ISSUE TITLE
Block PRs to main

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#437]
PRs targeting main directly should not be possible outside the PR bot to prevent the Gitflow model integrity and avoid confusion.
This ticket should cover the work to provide a mechanism to block such PRs.

**Comment by ipopescu** [comment]
Isn't this done @bradjohnl?

**Comment by bradjohnl** [comment]
@ipopescu Not totally as any Organization administrator, repository administrator, and user with the Maintain role is allowed to push to main (Through a pull request). It seems this is by default and cannot be changed.

It seems there is nothing preventing me from creating a PR targeting main instead of dev, somebody approves it by mistake and it gets merged to main.

I think this was the reason why this ticket was created. It happened that some PRs were created targeting main by mistake.

**Comment by bradjohnl** [comment]
There is no main branch anymore on the docs site, therefore this no longer applies
