### ISSUE TITLE
Automerge on approval

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#438]
To reduce manual intervention, the PRs which are approved and green on the build should be merged automatically unless they are draft PRs or have the "do not merge" label

**Comment by ipopescu** [comment]
Do we still need this @bradjohnl ?

**Comment by bradjohnl** [comment]
@ipopescu In my opinion it would be a small improvement which should not be too expensive to implement. We should also direct this question to the other users and maintainers of the documentation to see what they think.

It is much better to know that once a reviewer approves the PR, after the build goes green, it gets merged automatically instead of having to deal with the additional cognitive load of remembering to check it in like 15 minutes and hit the merge button.

**Comment by ipopescu** [comment]
Thanks, @bradjohnl. 
@devendran-m maybe we need to mark priority in these stories. That would help with triage. Most other ticketing systems have this in place.

**Comment by devendran-m** [comment]
Labelled P3 - Low priority

**Comment by ACStoneCL** [comment]
Closed as won't do.
