### ISSUE TITLE
Prevent CI from running on push and PR creation

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#439]
It seems that CI jobs are running twice reacting on on both push and PR creation events when opening a PR, leading to unnecessary resources usage.
Outside that this can lead to confusion and adds us more error surface.
Therefore this ticket aims to prevent CI from running on push and PR creation.

**Comment by ipopescu** [comment]
Is this still an issue @bradjohnl ?

**Comment by bradjohnl** [comment]
@ipopescu I think it is and what I have observed is that if you just specify the push as a trigger for the workflow run, then the checks for the PR do not work because Github Actions is not able to link your last push job status to the PR creation.
There must be a way to deal with this situation.
If a fix is found, you don't have to wait for the jobs to run again on the same commit after opening a PR, when they were successful when the same commit was pushed to your branch.

**Comment by ACStoneCL** [comment]
Completed by #1291
