### ISSUE TITLE
Won't do: How to use sidecar data for testing when building dApps

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#458]
double check existing docs and if they are sufficient for how to use sidecar data, this can be a won't do

**Comment by RitaMAllenCA** [comment]
@ipopescu Hello "i-pop" (that is your 'rap' name).  With the release of Sidecar becoming real, we should have solid documentation for anyone who is interested in using this.  As we will likely be encouraging connecting to the sidecar over the node itself, the need for this becomes more urgent.  This ticket is pretty old, but I suggest we repurpose it to its current usefulness.  I will put it in the next sprint and give it 13 points since you will likely need time to come up to speed on SSE sidecar.

**Comment by ipopescu** [comment]
Sounds good, @RitaMAllenCA. I see the requirements are empty although the title is self explanatory. If there are any additional details you would like to see, please let me know.

**Comment by ipopescu** [comment]
@RitaMAllenCA @darthsiroftardis @George-cl @sacherjj 
What we have here, waiting to be published, seems enough to me:
- https://github.com/casper-network/docs/blob/feat-sse_sidecar/source/docs/casper/operators/event-sidecar.md
- https://github.com/casper-network/docs/blob/feat-sse_sidecar/source/docs/casper/dapp-dev-guide/building-dapps/monitoring-events.md
We should close this card unless you want to see something else in the documentation. Moving this to review until I get confirmation that we can close it as a 'won't do'.
