### ISSUE TITLE
Polish and merge existing doc for redelegate option 

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/docs#862]
Here is the existing doc: [redelegate-old.md](https://github.com/casper-network/docs/files/10688959/redelegate-old.md).
Polish and merge it to the docs repository.

**Comment by ipopescu** [comment]
This is taking longer than 1 point due to the testing I want to do to check all the commands. I am currently blocked from building the redelegate.wasm in the "dev" branch. So, I need to follow up with the dev team and get unblocked.
Plus, I had to do a major refresh of the old document provided.

**Comment by RitaMAllenCA** [comment]
ok, please update the points to something more representative

**Comment by ipopescu** [comment]
I have the content, but 2 things block me to merge and close the card:
1. I want to be able to test the redelegate.wasm file against a live network such as the Testnet unless this is explicitly not required for this card, and the call can be tested later when we release 1.5. I could try to use NCTL on a Mac, but that will require additional setup, and I need to figure out how to delegate and redelegate using a local user and a local node.
2. The feat-1.5.0 branch in the docs is extremely behind. It needs to be rebased to dev, and that is additional work. I need to talk with Karan and Adam to see how to go about it. I cannot add my content because the prerequisites and delegate files have been refactored.

So, I am attaching the files I have here for safekeeping. I have them in my local branch as well.

   - [delegate.md](https://github.com/casper-network/docs/files/10711996/delegate.md)
   - [redelegate.md](https://github.com/casper-network/docs/files/10711997/redelegate.md)
   - PR #879
