### ISSUE TITLE
Document validator eviction

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#87]
In the operators' guide, develop an explanation for validator eviction. When does it happen? How to avoid it?

@afck write up a hackmd summary of validator eviction in Highway 2.0 
The writeup will become the input for documentation
Note - We still require documentation for Highway 2.0 despite the current ongoing work on Highway 3.0.

**Comment by ipopescu** [comment]
@sacherjj @Fraser999 @GloreenS Re-surfacing this card for discussion -- do we need this or should we close it?

**Comment by afck** [comment]
I don't have much to add to https://github.com/casper-network/casper-node/wiki/Recover-from-Validator-Ejection.
Maybe I can elaborate a bit on when you're considered inactive of faulty:

In the last block of each era _N_ the consensus algorithm checks whether there are _any_ messages from your validator node in that era that have been received by most of the other validators. Only if there is not a single such message does your node get marked as "inactive" in that block.
Similarly, it checks whether any two messages from your validator node contradict each other. If that is the case it gets marked as "faulty" in that block.

Usually that means:
* If you got marked as "inactive", probably your node has crashed or was offline for the duration of one whole era, i.e. at least from when the era began until when the era's last block was proposed.
* If you got marked as "faulty" you were probably running two nodes with the same validator key, or you restarted a node during the era, and deleted its unit file.

When the block gets executed the auction contract is run, as always at the end of the era. But if you were faulty or inactive you are now evicted, and don't take part in the auction anymore. You also don't receive any rewards for era _N_. The auction determines the validator set for the era after the next (because `auction_delay` is set to `1` on mainnet), i.e. for era _N + 2_. That means you will still be a validator (with a weight proportional to your stake) in the next era, _N + 1_, but after that you will not be a validator anymore and your slot will be given to the next highest bidder.

And even in the next era, _N + 1_:
* If you were inactive, you won't be assigned any leader slots, and won't be allowed to propose any blocks. Your node will only vote on other proposers' blocks if it comes back online, and can still receive rewards. (But even if it comes back online in era _N + 1_ it will get evicted for being offline in era _N_.)
* If you were faulty all your messages will be ignored. You won't be able to propose blocks or vote for them, and won't receive block rewards.

You remain evicted until you reactivate your bid, as described in the wiki.

**Comment by ipopescu** [comment]
@devendran-m please take a look at this ticket

**Comment by devendran-m** [comment]
@ipopescu , I am collating the contents shared by @sacherjj and @afck  This work will be done offline and outside sprint. The aim is to collate the details and give it a shape that is ready to be reviewed by content owners (Joe & Andreas) and other Tech Writers. The rough plan is to do it alongside Oct 4 - 18th Sprint cycle.

**Comment by ipopescu** [comment]
Thanks, @devendran-m!

**Comment by ipopescu** [comment]
This info is still useful, and the ticket contains what is needed to proceed. My ETA is a couple of points with reviews.

**Comment by ipopescu** [comment]
Extend https://docs.casperlabs.io/operators/bonding/ with this information. Keep ticket.

**Comment by ipopescu** [comment]
Hi @devendran-m, I am working on this ticket this sprint. Do you have anything more to add or share, as you mentioned [above](https://github.com/casper-network/docs/issues/87#issuecomment-1263391635)?
